version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: golem-backend
    restart: unless-stopped
    networks:
      - golem-network
    volumes:
      - ./data:/app/data
      - static-files:/app/staticfiles
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,golem-dev.biodata.ceitec.cz,127.0.0.1,backend,golem-backend
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-your-secure-key-here}
      - SECURE_SSL_REDIRECT=False
      - SESSION_COOKIE_SECURE=False
      - CSRF_COOKIE_SECURE=False
    depends_on:
      - postgres
    command: >
       bash -c "python manage.py makemigrations &&
           python manage.py migrate && python manage.py collectstatic --noinput &&
           gunicorn --worker-class=sync --workers=3 --bind=0.0.0.0:8000 --timeout=1800 --max-requests=1000 --max-requests-jitter=50 --graceful-timeout=300 --keep-alive=5 --worker-connections=1000 wsgi:application"

  nginx:
    image: nginx:1.25-alpine
    container_name: golem-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./ui/build/web:/usr/share/nginx/html
      -  static-files:/app/staticfiles
    depends_on:
      - backend
    networks:
      - golem-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: golem-certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - golem-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  postgres:
    image: postgres:15
    container_name: golem-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: genewebdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - golem-network

networks:
  golem-network:
    driver: bridge

volumes:
  postgres-data:
  static-files:
