# Generated by Django 5.1.6 on 2025-03-25 15:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganismGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('members', models.ManyToManyField(blank=True, related_name='organism_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organism Group',
                'verbose_name_plural': 'Organism Groups',
            },
        ),
        migrations.CreateModel(
            name='UserColorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('motif', 'Motif'), ('stage', 'Stage')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$', 'Enter a valid hex color code')])),
                ('stroke_width', models.PositiveSmallIntegerField(default=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'preference_type', 'name')},
            },
        ),
    ]
