# Generated by Django 5.1.6 on 2025-04-09 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotifAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_name', models.CharField(db_index=True, max_length=255)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('group', 'Group'), ('user', 'User')], default='public', max_length=10)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motif_access', to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motif_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motif Access',
                'verbose_name_plural': 'Motif Access',
                'unique_together': {('motif_name', 'access_type', 'group', 'user')},
            },
        ),
    ]
