# Generated by Django 5.1.6 on 2025-04-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_motifaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='organism_filename',
            field=models.CharField(db_index=True, default='default_organism.fasta', max_length=255),
        ),
        migrations.AlterField(
            model_name='organismaccess',
            name='organism_name',
            field=models.CharField(db_index=True, help_text="Enter the organism filename (e.g., 'Allium_cepa.fasta.fasta')", max_length=255),
        ),
    ]
