# Generated by Django 5.1.6 on 2025-03-25 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('organism', models.CharField(db_index=True, max_length=255)),
                ('motifs', models.JSONField(default=list)),
                ('stages', models.JSONField(default=list)),
                ('settings', models.JSONField(default=dict)),
                ('filtered_results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism_name', models.CharField(db_index=True, max_length=255)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('group', 'Group'), ('user', 'User')], default='public', max_length=10)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism_access', to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organism_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organism_name', 'access_type', 'group', 'user')},
            },
        ),
    ]
