# Generated by Django 5.1.6 on 2025-02-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
