# Generated by Django 5.1.6 on 2025-03-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_analysishistory_filtered_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysishistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
