import 'package:geneweb/analysis/motif.dart';

class MotifPresets {
  static List<Motif> presets = [
    Motif(
        name: 'Arabidopsis.telobox',
        isPublic: false,
        definitions: ['CCCTAAAC', 'CCTAAACC', 'CTAAACCC', 'TAAACCCT', 'AAACCCTA', 'AACCCTAA', 'ACCCTAAA']),
    Motif(name: 'Arabidopsis.telobox.generic', isPublic: false, definitions: ['NGGNNTN', 'NGGNTN']),
    Motif(name: 'Arabidopsis.siteII', isPublic: false, definitions: ['TGGGCC', 'TGGGCT', 'GGNCCCAC', 'GTGGNCCC']),
    Motif(name: 'SHORT LAT52/56', definitions: ['GTGA']),
    Motif(name: 'POLLEN1LeLAT52', definitions: ['AGAAA']),
    Motif(name: 'LONG LAT52/56', definitions: ['TGTGGTTATATA']),
    Motif(name: 'LONG LAT56/59', definitions: ['GAAWTTGTGA']),
    Motif(name: 'TEF1 box', definitions: ['ARGGRYNNNNNGYA']),
    Motif(name: 'PB', definitions: ['TGTGGTT']),
    Motif(name: 'TCCACCATA', definitions: ['TCCACCATA']),
    Motif(name: 'GTGANTG10', definitions: ['CCAC']),
    Motif(name: 'TATA-box', definitions: ['TATAWAW']),
    Motif(name: 'TATA-box short', definitions: ['TATAWA']),
    Motif(name: 'TC', definitions: ['TTCTTC']),
    Motif(name: 'LGC1', definitions: ['GGCTGAATTT']),
    Motif(name: 'KAN4 Short', definitions: ['GAATAT']),
    Motif(name: 'KAN4 Long', definitions: ['GAATATTCCT']),
    Motif(name: 'NTP303', definitions: ['AAATGA']),
    Motif(name: 'DUO1 germline', definitions: ['DNGTGGV']),
    Motif(name: 'DUO1 enhance', definitions: ['YAACYGY']),
    Motif(name: 'ARR1AT', definitions: ['NGATT']),
    Motif(name: 'CAATBOX1', definitions: ['CAAT']),
    Motif(name: 'CACTFTPPCA1', definitions: ['CACGTG']),
    Motif(name: 'DOFCOREZM', definitions: ['AAAG']),
    Motif(name: 'GATABOX', definitions: ['GATA']),
    Motif(name: 'GT1CONSENSUS', definitions: ['GRWAAW']),
    Motif(name: 'ROOTMOTIFTAPOX1', definitions: ['ATATT']),
    Motif(name: 'WRKY71OS', definitions: ['TGAC']),
    Motif(name: 'BIHD1OS', definitions: ['TGTCA']),
    Motif(name: 'CCAATBOX1', definitions: ['CCAAT']),
    Motif(name: 'CURECORECR', definitions: ['GTAC']),
    Motif(name: 'EBOXBNNAPA', definitions: ['CANNTG']),
    Motif(name: 'GT1GMSCAM4', definitions: ['GAAAAA']),
    Motif(name: 'IBOXCORE', definitions: ['GATAA']),
    Motif(name: 'INRNTPSADB', definitions: ['YTCANTYY']),
    Motif(name: 'MYBCORE', definitions: ['CNGTTR']),
    Motif(name: 'MYBST1', definitions: ['GGATA']),
    Motif(name: 'MYCCONSENSUSAT', definitions: ['CANNTG']),
    Motif(name: 'NODCON2GM', definitions: ['CTCTT']),
    Motif(name: 'OSE2ROOTNODULE', definitions: ['CTCTT']),
    Motif(name: 'POLASIG1', definitions: ['AATAAA']),
    Motif(name: 'RAV1AAT', definitions: ['CAACA']),
    Motif(name: 'SEF4MOTIFGM7S', definitions: ['RTTTTTR']),
    Motif(name: 'TAAAGSTKST1', definitions: ['TAAAG']),
    Motif(name: 'TATABOX5', definitions: ['TTATTT']),
    Motif(name: 'TL1ATSAR', definitions: ['CTGAAGAAGAA']),
    Motif(name: 'M1561_1.01', definitions: ['RGTCAACK']),
    Motif(name: 'M0769_1.01', definitions: ['YTGATTGA']),
    Motif(name: 'Gap-box_motif', definitions: ['CAAATGAA']),
    Motif(name: 'Bellringer/replumless/pennywise', definitions: ['AAATTAAA']),
    Motif(name: 'Allium.Cepa.telobox', isPublic: false, definitions: [
      'CTCGGTTATGGGC',
      'TCGGTTATGGGCT',
      'CGGTTATGGGCTC',
      'GGTTATGGGCTCG',
      'GTTATGGGCTCGG',
      'TTATGGGCTCGGT',
      'TATGGGCTCGGTT',
      'ATGGGCTCGGTTA',
      'TGGGCTCGGTTAT',
      'GGGCTCGGTTATG',
      'GGCTCGGTTATGG',
      'GCTCGGTTATGGG',
    ]),
    Motif(name: 'Allium.Cepa.7Nt', isPublic: false, definitions: [
      'TATGGGC',
      'ATGGGCT',
      'TGGGCTC',
      'GGGCTCG',
      'GGCTCGG',
      'GCTCGGT',
      'CTCGGTT',
      'TCGGTTA',
      'CGGTTAT',
      'GGTTATG',
      'GTTATGG',
      'TTATGGG',
    ]),
  ]..sort(((a, b) => a.name.compareTo(b.name)));
}
