## Use the official Flutter image
#FROM cirrusci/flutter:stable
#
## Set the working directory
#WORKDIR /app
#
## Copy the pubspec.yaml and other necessary files
#COPY pubspec.yaml .
#COPY pubspec.lock .
#
## Get dependencies
#RUN flutter pub get
#
## Copy the rest of your application code
#COPY . .
#
## Run your application (change the command as needed)
#CMD ["flutter", "run", "--web", "--debug"]
