name: geneweb
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.3
  charts_flutter: ^0.12.0
  equatable: ^2.0.3
  file_picker: ^5.2.3
  excel: ^2.0.0-null-safety-3
  universal_file: ^1.0.0
  flex_color_picker: ^2.5.0
  archive: ^3.3.1
  truncate: ^3.0.1
  collection: ^1.16.0
  sanitize_filename: ^1.0.4
  flutter_svg: ^1.0.0
  file_saver: ^0.1.1
  share_plus: ^6.3.0
  flutter_native_splash: ^2.1.0
  csv: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#eeeeee"
  image: assets/logo_prif@3x.png
